spring.application.name=SpringAiQuickStart

server.port=8080

# 配置DeepSeek的基础url、密钥和使用模型
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.api-key=sk-7a54c9235e804dca927eae70fe96fc13
spring.ai.deepseek.chat.model=deepseek-v4-pro

# 介于0和2之间 0表示随机性最小 2表示随机性最大
spring.ai.deepseek.chat.temperature=0.8

spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas
spring.ai.zhipuai.api-key=f733a84e5ac446c8924da8302d508a4f.nQH0kKAp2PncBPsn
spring.ai.zhipuai.chat.options.model=GLM-4.6V
spring.ai.zhipuai.embedding.options.model=embedding-3